#!/usr/bin/env node

var adventure = require('adventure');
var shop = adventure('jquery-adventure');

shop.add('$( document ).ready()', function () { return require('./problems/ready') });
shop.add('data attribute', function () { return require('./problems/data_attribute') });
shop.add('querying dom', function () { return require('./problems/single_dom_query') });
shop.execute(process.argv.slice(2));
